### ISSUE TITLE
Semantic Mask Tested on CelebA

### ISSUE THREAD

**Issue by Kelu007** [Wuziyi616/SlotDiffusion#1]
Thanks for your great work. I've tested your model on images from CelebA, but found some strange results. It seems that every semantic mask is same and the compositional results seem not so good as those in paper. Could you please help me?
<img width="448" alt="image" src="https://github.com/Wuziyi616/SlotDiffusion/assets/48619529/fd8e7311-17eb-41c9-b17a-0279a051bf6f">
<img width="1037" alt="image" src="https://github.com/Wuziyi616/SlotDiffusion/assets/48619529/7a03982e-cff9-4d38-abb9-f4e92cc5b326">

**Comment by Wuziyi616** [comment]
Can you first check if the reconstruction results are correct? This is a sanity-check to make sure the environment, data, code running, etc. is correct. The images you posted here look weird to me as the background/some parts of faces look blurry. This is usually a sign of running too few diffusion steps.

But let me be very frank, the compositional face generation results in the paper are cherry-picked, so I won't be surprised if normal examples are not as good as them (but our normal examples are still much better than baselines' results).

For the segmentation masks, yes this is what we get (see attached a wandb logged results of this training run). I think it's because of a pose bias on the CelebA dataset. Most of the faces are in the same pose so the model just learns that. FFHQ might be a better dataset to try as shown in [LSD](https://arxiv.org/pdf/2303.10834.pdf), where they get more meaningful segmentations.

![recon_0_e88ac48aae7ca1947e5b](https://github.com/Wuziyi616/SlotDiffusion/assets/37072215/1ea76a1b-74cc-449e-8237-0c9ef0c1559d)

**Comment by Kelu007** [comment]
Thanks for your reply. I'll try as you suggested.

**Comment by Wuziyi616** [comment]
Feel free to re-open the issue if you have further questions
